<?php
$Browsers = array (
	'abrowse[ /\-]([\d.]+)', 'ABrowse',
	'amaya/([\d.]+)', 'Amaya',
	'Arachne/([\d.]+)', 'Arachne',
	'Aweb[/ ]([\d.]+)', 'AWeb',
	'beonex/([\d.]+)', 'Beonex',
	'BrowseX.*\(([\d.]+)', 'BrowseX',
	'camino/([\d.]+)', 'Camino',
	'curl[ /]([\d.]+)', 'Curl',
	'deskbrowse/([\d.]+)', 'DeskBrowse',
	'dillo/([\d.]+)', 'Dillo',
	'ELinks[ /][\(]*([\d.]+)', 'ELinks',
	'Epiphany/([\d.]+)', 'Epiphany',
	'Flock/([\d.]+)', 'Flock',
	'galeon/([\d.]+)', 'Galeon',
	'ibrowse[ /]([\d.]+)', 'IBrowse',
	'icab[/ ]([\d.]+)', 'ICab',
	'Iceweasel/([\d.]+)', 'IceWeasel',
	'K-Ninja[ /]([\d.]+)', 'K-Ninja',
	'K-Meleon[ /]([\d.]+)', 'K-Meleon',
	'Kazehakase[ /]([\w.]+)', 'Kazehakase',
	'Konqueror/([\d.]+)', 'Konqueror',
	'Links[ /]\(([\d.]+)', 'Links',
	'Lobo/([\d.]+)', 'Lobo',
	'lynx/([\w.]+)', 'Lynx',
	'minimo/([\d.]+)', 'Minimo',
	'Mosaic[ /]([\w.]+)', 'Mosaic',
	'netscape\d?/([\d.]+)', 'Netscape',
	'NetSurf/([\d.]+)', 'NetSurf',
	'', 'OffByOne',
	'omniweb/[ a-z]?([\d.]+)', 'OmniWeb',
	'Oregano[\d]?[ /](\d.+)', 'Oregano',
	'UP\.(?:Browser)?[ /]([\w.]+)', 'OpenWave',
	'Opera Mini[ /]([\d.]+)', 'Opera Mini',
	'Opera[ /]([\d.]+)', 'Opera',
	'NetFront[ /]([\d.]+)', 'NetFront',
	'psp.*playstation.*portable\D*([\w\.]+)', 'PlayStation',
	'Shiira/([\d.]+)', 'Shiira',
	'safari/([\d.]+)', 'Safari',
	'SeaMonkey/([\w.]+)', 'SeaMonkey',
	'songbird/([\d.]+)', 'Songbird',
	'Firefox/([\d.]+)', 'Swiftfox',
	'w3m/([\d.]+)', 'W3M',
	'Wget[ /]([\d.]+)', 'Wget',
	'voyager[ /]([\d.]+)', 'Voyager',
	'MSPIE[ /]([\d.]+)', 'Pocket Internet Explorer',
	'\(compatible; MSIE[ /]([\d.]+)', 'MSIE',
	'Firefox/([\d.]+)', 'Firefox',
	'rv:([\w.]+)', 'Mozilla'
	);
?>