<?php
$Robots = array (
	'Alexa' => 'ia_archiver',
	'AltaVista',
	'AOLserver',
	'Aport',
	'Ask Jeeves',
	'AnswerBus',
	'Baidu',
	'Bigsearch',
	'BitTorrent' => 'BTbot',
	'Bloglines',
	'Cazoodle',
	'Cosmix',
	'Cynthia Says' => 'cynthia',
	'Dr.Watson' => 'Watson',
	'Drupal',
	'eBay',
	'Entireweb' => 'Speedy Spider',
	'Feed Validator' => 'FeedValidator',
	'Exabot',
	'FindLinks',
	'Gigabot',
	'Google',
	'Grub',
	'Gulliver',
	'Hatena',
	'HostTracker',
	'HTTPClient',
	'IAsk',
	'IBM Crawler' => 'www.almaden.ibm.com/cs/crawler',
	'Infoseek',
	'Inktomi',
	'Java',
	'Jigsaw Validator' => 'W3C_CSS_Validator',
	'Larbin',
	'Link Checker' => 'checklink',
	'libWWW',
	'Lorkyll',
	'LWP',
	'Lycos',
	'Mnogo',
	'MSN',
	'Netoskop',
	'Nutch' => 'NutchOrg',
	'Onet',
	'PHP',
	'Planet',
	'Psbot',
	'Scrubby',
	'Sogou',
	'Szukacz',
	'Technorati',
	'Twiceler',
	'Ultraseek',
	'UltraSpider',
	'Voila',
	'Vortex',
	'W3C Validator' => 'W3C_Validator',
	'W3SiteSearch',
	'WDG Validator' => 'WDG_Validator',
	'WebCrawl',
	'Webfind',
	'WebMiner',
	'Webmon',
	'WordPress',
	'WP' => 'netsprint',
	'WWWC',
	'WWWeasel',
	'Yahoo',
	'Yandex',
	'Zeus',
	'ZyBorg',
	'?' => 'robot',
	'?' => 'spider',
	'?' => 'crawler'
	);
?>