<?php
$Array = array (
	'Stats' => array (
		'Antipixel' => array ('default/silver.png', 0),
		'CountPhrases' => array (0, 1),
		'CountRobots' => array (1, 1),
		'IgnoredIPs' => array ('127.0.0.1', 3),
		'Keywords' => array ('', 3),
		'LogEnabled' => array (1, 1),
		'LogFile' => array (1, 1),
		'Monitor' => array (1, 1),
		'Monthly' => array (1, 1),
		'Referrers' => array ('localhost', 3),
		'SendHeaders' => array (1, 1),
		'StatsEnabled' => array (1, 1),
		'Time' => array (86400, 2),
		'Backups' => array (
			'profile' => array ('full', 0),
			'replacedata' => array (1, 1),
			'tablesstructure' => array (0, 1),
			'time' => array (0, 0),
			'usertables' => array ('', 3),
			),
		'CollectData' => array (
			'browsers' => array (1, 1),
			'cookies' => array (1, 1),
			'flash' => array (1, 1),
			'hosts' => array (1, 1),
			'java' => array (1, 1),
			'javascript' => array (1, 1),
			'keywords' => array (1, 1),
			'langs' => array (1, 1),
			'oses' => array (1, 1),
			'referrers' => array (1, 1),
			'robots' => array (1, 1),
			'screens' => array (1, 1),
			'sites' => array (1, 1),
			'websearchers' => array (1, 1)
			),
		),
	'Cache' => array (
		'RegenerateForAdmin' => array (1, 1),
		'DBCache' => array (
			'archive' => array (15, 2),
			'detailed' => array (3, 2),
			'general' => array (15, 2),
			'technical' => array (15, 2),
			'time' => array (15, 2),
			),
		),
	'GUI' => array (
		'AntyFlood' => array (2, 2),
		'BlockedIPs' => array ('', 3),
		'CheckVersionTime' => array (600, 2),
		'DateFormat' => array ('d.m.Y H:i:s', 0),
		'Debug' => array (0, 1),
		'DefaultLang' => array ('en', 0),
		'DefaultPage' => array ('general', 0),
		'DefaultTheme' => array ('Silver', 0),
		'EditMode' => array (1, 1),
		'Header' => array ('%statsfor% <a href="http://{servername}" tabindex="{tindex}">{servername}</a><br />
<small>%collectedfrom% {startdate}</small>', 0),
		'IgnoredAmount' => array (30, 2),
		'LogsAmount' => array (50, 2),
		'Offset' => array (0, 2),
		'MaxAdminGroupOptions' => array (50, 2),
		'Maintenance' => array (0, 1),
		'Pass' => array ('', 0),
		'RemeberTime' => array (1209600, 2),
		'TimeZone' => array ('UTC', 0),
		'WeekStartDay' => array (1, 2),
		'WhoisLink' => array ('http://www.ripe.net/fcgi-bin/whois?searchtext=[data]', 0),
		'Charts' => array (
			'defaultview' => array ('all', 2),
			'showlevels' => array (1, 1),
			'showtooltips' => array (1, 1)
			),
		'Detailed' => array (
			'amount' => array (30, 2),
			'period' => array (30, 2),
			'detailsamount' => array (30, 2),
			'keepalldata' => array (1, 1),
			'maxpages' => array (10, 2),
			'showdetails' => array (1, 1),
			'showrobots' => array (1, 1),
			),
		'HowMany' => array (
			'browsers' => array (15, 2),
			'cookies' => array (3, 2),
			'flash' => array (10, 2),
			'hosts' => array (15, 2),
			'java' => array (3, 2),
			'javascript' => array (3, 2),
			'keywords' => array (15, 2),
			'langs' => array (15, 2),
			'oses' => array (15, 2),
			'referrers' => array (15, 2),
			'robots' => array (15, 2),
			'screens' => array (10, 2),
			'sites' => array (30, 2),
			'vbrowsers' => array (15, 2),
			'voses' => array (15, 2),
			'websearchers' => array (15, 2)
			),
		'Path' => array (
			'mode' => array (0, 1),
			'prefix' => array ('index.php?vars=', 0),
			'separator' => array ('&amp;', 0),
			'suffix' => array ('', 0),
			),
		)
	);
?>